name: CI

on: [ push ]

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK  17.0.7
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 17.0.7
    - name: clean build
      run: ./gradlew clean test --info --stacktrace